# Generated by Django 4.2.5 on 2023-09-20 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('room', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('userType', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedNumber', models.IntegerField()),
                ('bedUsername', models.CharField(max_length=10)),
                ('bedUserTel', models.CharField(max_length=13)),
                ('bedUserNo', models.CharField(max_length=10)),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domitory_api.dormitory')),
            ],
        ),
    ]
