# Generated by Django 4.2.5 on 2023-09-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domitory_api', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dormitory',
            name='floor',
        ),
    ]
