# Generated by Django 4.2.5 on 2023-09-20 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domitory_api', '0003_remove_dormitory_floor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedinfo',
            old_name='RoomId',
            new_name='dormitory',
        ),
    ]
