# Generated by Django 4.2.5 on 2023-09-20 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domitory_api', '0004_rename_roomid_bedinfo_dormitory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedinfo',
            old_name='dormitory',
            new_name='dormitory_id',
        ),
    ]
