# Generated by Django 4.2.5 on 2023-09-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domitory_api', '0005_rename_dormitory_bedinfo_dormitory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bedinfo',
            old_name='dormitory_id',
            new_name='dormitory',
        ),
    ]
